imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: app.pdo_session_handler
    fragments: ~
    http_method_override: true
    assets:
        packages:
            frontend:
                version: 1
                version_format: null
                base_path: '%asset_base_path%'

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        "%kernel.root_dir%/../src/AppBundle/Resources/views/Security": Security
        "%kernel.root_dir%/../src/AppBundle/Resources/views/Frontend": Frontend
        "%kernel.root_dir%/../src/AppBundle/Resources/views/Backend": Backend
        "%kernel.root_dir%/../src/AppBundle/Resources/views/Layouts": Layouts
        "%kernel.root_dir%/../src/AppBundle/Resources/views/Partial": Partial

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
jms_serializer:
    handlers:
        datetime:
            default_format: "Y-m-d H:i:s" # ISO8601
            default_timezone: "UTC" # defaults to whatever timezone set in php.ini or via date_default_timezone_set
    property_naming:
        separator: ~
    metadata:
        directories:
            AppBundle:
                path: '@AppBundle/Resources/config/serializer'
                namespace_prefix: "AppBundle"
fos_rest:
    routing_loader:
        default_format: json
    serializer:
        serialize_null: true
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json: true
            html: true
        templating_formats:
            html: true
        default_engine: twig
        failed_validation: HTTP_BAD_REQUEST
    format_listener:
        enabled: true
        rules:
            - { path: ^/, stop: true }
    exception:
        codes:
            #'AppBundle\Exception\InvalidException': 400
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener:
        decoders:
            json: fos_rest.decoder.json
    disable_csrf_role: ~
knp_paginator:
    page_range: 7
    template:
        pagination: '@Partial/sliding.html.twig'