article_list:
  path: /article/
  defaults:
    _controller: AppBundle:Frontend\Article:index
article_info:
  path: /article/{id}.html
  defaults:
    _controller: AppBundle:Frontend\Article:info
  requirements:
    id: ^([1-9])|([1-9]\d+)$
article_category:
  path: /article/{category}/
  defaults:
    _controller: AppBundle:Frontend\Article:category
case_list:
  path: /case/
  defaults:
    _controller: AppBundle:Frontend\Case:index
case_info:
  path: /case/{id}.html
  defaults:
    _controller: AppBundle:Frontend\Case:info
  requirements:
    id: ^([1-9])|([1-9]\d+)$
case_category:
  path: /case/{category}/
  defaults:
    _controller: AppBundle:Frontend\Case:category
tag_list:
  path: /tags/{tagId}/
  defaults:
    _controller: AppBundle:Frontend\Tags:index
  requirements:
    tagId: ^([1-9])|([1-9]\d+)$
job_list:
  path: /job_openings/
  defaults:
    _controller: AppBundle:Frontend\JobOpenings:index
job_info:
  path: /job_openings/{id}.html
  defaults:
    _controller: AppBundle:Frontend\JobOpenings:info
  requirements:
    id: ^([1-9])|([1-9]\d+)$