AppBundle\Entity\Cases:
    type: entity
    table: cases
    repositoryClass: AppBundle\Entity\CasesRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        categoryId:
            type: integer
            nullable: false
            unsigned: false
            column: category_id
        title:
            type: string
            nullable: false
            length: 255
            fixed: false
        thumbnail:
            type: string
            nullable: true
            length: 255
            fixed: false
        banner:
            type: string
            nullable: true
            length: 255
            fixed: false
        introduce:
            type: text
            nullable: true
            length: 65535
            fixed: false
        content:
            type: text
            nullable: false
            length: 65535
            fixed: false
        deleted:
            type: boolean
            nullable: false
        recommend:
            type: boolean
            nullable: false
        published:
            type: boolean
            nullable: true
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        price:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: 价格
            default: '1'
        showPrice:
            type: boolean
            nullable: false
            comment: 显示价格
            default: '0'
            column: show_price
        video:
            type: string
            nullable: true
            length: 255
            fixed: false
        rank:
            type: integer
            nullable: false
            unsigned: false
            comment: 排序
            default: '1'
    lifecycleCallbacks:
        prePersist: [createdAtHandle]
