AppBundle\Entity\Tag:
    type: entity
    table: tag
    repositoryClass: AppBundle\Entity\TagRepository
    uniqueConstraints:
        unique_name:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: 标签名称
    lifecycleCallbacks: {  }
