<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\LockMode;
/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends AbstractRepository
{
    /**
     * @param $id
     * @param int $lockMode
     * @param null $lockVersion
     * @return Article|object
     */
    public function findWithCategory($id, $lockMode = null, $lockVersion = null)
    {
        $entity = parent::find($id,$lockMode,$lockVersion);
        if($entity){
            $category = $this->_em->getRepository('AppBundle:Category')->find($entity->getCategoryId());
            $entity->setCategory($category);
        }
        return $entity;
    }

    /**
     * @param int $limit
     *
     * @return array
     */
    public function recommendArticle($limit = 5)
    {
        return $this->findBy(['deleted'=>0,'recommend'=>1],['rank'=>'DESC','id'=>'DESC'],$limit);
    }

}
