<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\LockMode;

/**
 * CasesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasesRepository extends AbstractRepository
{
    /**
     * @param $id
     * @param int $lockMode
     * @param null $lockVersion
     * @return Article|object
     */
    public function findWithCategory($id, $lockMode = LockMode::NONE, $lockVersion = null)
    {
        $entity = parent::find($id,$lockMode,$lockVersion);
        if($entity){
            $category = $this->_em->getRepository('AppBundle:Category')->find($entity->getCategoryId());
            $entity->setCategory($category);
        }
        return $entity;
    }

    public function homeCases($limit = 3)
    {
        return $this->findBy(['deleted'=>0,'recommend'=>1],['id'=>'DESC'],$limit);
    }
}
