<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * TagMapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagMapRepository extends AbstractRepository
{
}
